<?php
//class gameAccount is defined
class gameAccount{
    //variables are declared and made either protected or public
    public $name;
    public $email;
    protected $account_number;
    protected $password;
    //function construct creates the variables to be set
    function __construct($person_name, $account_password, $number_account, $account_email){
        $this->name=$person_name;
        $this->password=$account_password;
        $this->account_number=$number_account;
        $this->email=$account_email;
    }
    //the set_$var sets the variables with the associated variables used on the index
    function set_name($new_name){
        $this->name = $new_name;
    }
    protected function set_password($new_password){
        $this->password = $new_password;
    }
    protected function set_account_number($new_number){
        $this->account_number=$new_number;
    }
    function set_email($new_email){
        $this->email=$new_email;
    }
    //if their is a name, it is returned on the index.php
    function get_name(){
    return $this->name;
}
    protected function get_password(){
        return $this->password;
    }
    protected function get_account_number(){
        return $this->account_number;
    }
    function get_email(){
        return $this->email;
    }


}
//class xboxAccount is a child function of gameAccount
class xboxAccount extends gameAccount{
    //variables are declared as public
    public $name;
    public $username;
    //construct is started to call variables
    function __construct($person_name, $username, $account_password, $number_account, $account_email)
    {
        //parent function __construct is called to declare past variables
        parent::__construct($person_name, $account_password, $number_account, $account_email);
        $this->name=$person_name;
        $this->username = $username;
        $this->password=$account_password;
        $this->account_number=$number_account;
        $this->email=$account_email;
    }
    //only username is used set/get to declare new function/variable
    function set_username($new_username){
        $this->username=$new_username;
    }
    function get_username(){
        return $this->username;
    }
}

abstract class Games{
    public $name;
    public $rating;
    public $release;
    public $describe;
    public function game(){
        return $this->name . ' is a game about ' . $this->describe . '. It was released in ' . $this->release . ' and was given a ' . $this->rating . ' rating.';
    }
}
class Halo extends Games{
    public function games()
    {
        return parent::game(); // TODO: Change the autogenerated stub
    }
}
class steam_user{
    public $username;
    public $password;
    public static $min_password = 8;
    public static function min(){
        if(strlen($password) >= self::$min_password){
            return true;
        }
        else{
            return false;
        }
    }

}
class gamerServices{
    public $gamesvr1 = 'Xbox';
    public $gamesvr2 = 'PSN';
    public $gamesvr3 = 'Steam';
}
$gameservice = new gamerServices();
foreach($gameservice as $key => $value){
    print "$key => $value\n";
}

?>